### ISSUE TITLE
voom pandoc does not work

### ISSUE THREAD

**Issue by pinggit** [vim-voom/VOoM#12]
Voom markdown works fine.
but I want to ignore the comment line in fenced code block, so I tried:
```
:Voom pandoc
```

but it does not work.
do I miss anything?

**Comment by pinggit** [comment]
I tested again, and it looks working.

so what I did wrong is:
```
:set ft=pandoc
:Voom
or
:Voom pandoc
```
and now it works with:
```
:set ft=markdown
:Voom pandoc
```

is there a way that I can use Voom pandoc as default for markdown files?

**Comment by vim-voom** [comment]
> is there a way that I can use Voom pandoc as default for markdown files?

You can change "g:voom_ft_modes" and "g:voom_default_mode".

**Comment by pinggit** [comment]
thanks. that works.
