### ISSUE TITLE
Support root and linked files in LaTeX

### ISSUE THREAD

**Issue by wookayin** [vim-voom/VOoM#14]
In LaTeX documents where the entire document is splitted into multiple files and source tex files, we can only see the voom outlines of each individual source files (not the whole outline). 

An example content of `01_introduction.tex`:
```
%!TEX root = main_doc.tex

\section{Introduction}
% ...
```

The VooM buffer shows:
```
01_introduction.tex
= |Introduction
```

Is there any way to extend so we can see the whole document structure in VooM? It means that VooM should be aware of such directives (like `%!TEX root`) and multiple source files linked to one another.

**Comment by vim-voom** [comment]
No. This is not possible and I have no desire to implement such
feature. Each VOoM outline is strictly for one Vim buffer. For working
with files there are file managers. There is also Leo, it works both
as an outliner and project manager:
https://github.com/leo-editor/leo-editor .
