### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by jhidding** [vim-voom/VOoM#8]
Hi, I created a fork that has Python3 support. Almost everything works for me now (except closing a Voom panel, that raises an error). I haven't created a pull request yet, since it would clearly break things for python2. I have never hacked into vim-scripts before, so maybe you have an idea howto merge the two in a compatible manner.
Cheers!

**Comment by vim-voom** [comment]
On 11/7/16, Johannes Hidding <notifications@github.com> wrote:
> Hi, I created a fork that has Python3 support. Almost everything works for
> me now (except closing a Voom panel, that raises an error). I haven't
> created a pull request yet, since it would clearly break things for python2.
> I have never hacked into vim-scripts before, so maybe you have an idea howto
> merge the two in a compatible manner.
> Cheers!

I plan to release new VOoM version 5.2 soon. It works with both Python
2 and 3. There are no new features other than Python 3 support. It is
important to have Python 3 support. Some Linux distros don't provide
Vim that works with both Pythons.

Python 3 version is slightly slower than Python 2.
There is also a Vim bug with Python 3, it can break VOoM outline
operations: https://github.com/vim/vim/issues/1053

**Comment by vim-voom** [comment]
On 11/7/16, Johannes Hidding <notifications@github.com> wrote:
> Hi, I created a fork that has Python3 support. Almost everything works for
> me now (except closing a Voom panel, that raises an error).

Probably related: Error message
    E937: Attempt to delete a buffer that is in use
When doing:bw, :bd, :bun in a VOoM Tree buffer.

This is caused by Patch 7.4.2324:
https://groups.google.com/forum/#!topic/vim_dev/mfq_VxRaLNA

This error can be ignored--the Tree buffer is wiped on anyway somehow.
My current fix is to catch error E937.

**Comment by jhidding** [comment]
Cool! I'll await v5.2 then :)

**Comment by vim-voom** [comment]
Done in VOoM v5.2.

**Comment by naught101** [comment]
Yay, thank you :)
